---
title: "code_states() Regex Table"
author: "Bernhard Bieri"
date: "`r Sys.Date()`"
output: rmarkdown::html_vignette
vignette: >
  %\VignetteIndexEntry{code_states() Regex Table}
  %\VignetteEngine{knitr::rmarkdown}
  %\VignetteEncoding{UTF-8}
---

```{r setup, include = FALSE}
knitr::opts_chunk$set(
  collapse = TRUE,
  comment = "#>",
  fig.align = "center",
  out.width = '\\textwidth'
)
```

The table below is the internal dataset that is used to translate country
names into an extended set of
[Correlates of War (COW)](https://correlatesofwar.org/) character codes.
Built upon the regex list in the excellent 
[{countrycode}](https://vincentarelbundock.github.io/countrycode/) package,
it contains additional codes for historical states and other international
entities. You can download the R dataframe directly 
[here](https://github.com/globalgov/manystates/blob/main/R/sysdata.rda?raw=true)
.

```{r}
countryregex <- readRDS("countryregex.rds")
knitr::kable(dplyr::arrange(countryregex, Label))
```