# Test GW Dataset

#This template is used by the export_data() function of the qData package to render a test file in the qStates package.
#The user should run these tests when using the export_data() function on a new raw dataset to ensure completeness and coherence in the database.

# Note that the chunks in parentheses are tests that are adapted to the new structure of the output generated by export_data(), namely a list of dataframes. 

library(pointblank)

test_that("object is correct", {
  expect_col_exists(states[[states[[GW]]]], vars("ID"))
  expect_col_exists(states[[states[[GW]]]], vars(Beg))
  expect_col_exists(states[[states[[GW]]]], vars(End))
})

# # Uniformity tests (countries have a numerical states[[GW]]_Nr, a unique string ID, a beginning and an end of tenure as well as a name.)
# test_that("object is correct", {
#   expect_col_exists(states[[states[[GW]]]], vars(states[[GW]]_Nr))
#   expect_col_exists(states[[states[[GW]]]], vars(ID))
#   expect_col_exists(states[[states[[GW]]]], vars(Beg))
#   expect_col_exists(states[[states[[GW]]]], vars(End))
#   expect_col_exists(states[[states[[GW]]]], vars(Label))
# })

test_that("missing obsevarsions are reported correctly", {
  expect_length(grepl("-", states[[states[[GW]]]]), 0)
  expect_length(grepl("n/a", states[[GW]]), 0)
  expect_length(grepl("N/A", states[[GW]]), 0)
})

# #Tests that missing observations are reported correctly.
# test_that("missing observations are reported correctly", {
#   expect_length(grepl("-", states[[states[[GW]]]]), 0)
#   expect_length(grepl("n/a", states[states[[GW]]]), 0)
#   expect_length(grepl("N/A", states[states[[GW]]]), 0)
# })


test_that("dates are standardised", {
  expect_col_is_date(states[[GW]], vars(Beg))
  expect_col_is_date(states[[GW]], vars(End))
  expect_length(grepl("/", states[[GW]]), 0)
})

# More restrictive test that ensure dates are also in the correct format
# #Set up a date checking function. Takes a vector and a date format as inputs (source: https://gist.github.com/micstr/69a64fbd0f5635094a53)
# is_date = function(x, format) {
#   formatted = try(as.Date(x, format), silent = TRUE)
#   return(as.character(formatted) == x)
# }
# 
# #Setting the YMD format
# date_format = "%Y-%m-%d"
# 
# #Running the tests on the list of dataframes that the export data function created.(source for syntax: https://stackoverflow.com/questions/47443365/how-to-extract-certain-columns-from-a-list-of-data-frames)
# test_that("dates are in the correct format (ymd)", {
#   expect_equal(is_date(states[[{{{dat}}}]][, "Beg"], date_format),TRUE)
#   expect_equal(is_date(states[[{{{dat}}}]][, "End"], date_format),TRUE)
# })

# Tests that the labels are standardized 
test_that("labels are standardised", {
  expect_length(grepl("U.S.", states[[GW]]), 0)
  expect_length(grepl("U.K.", states[[GW]]), 0)
  expect_length(grepl("?", states[[GW]]), 0)
  expect_length(grepl("NANA.", states[[GW]]), 0)
})