#' Code states
#' @description
#'   This function allows for the identification of countries in a text.
#' @param text A vector of text to search for country names within.
#' @param code Logical whether the function should return the three-letter
#'   abbreviation (an extended version of ISO-3166 alpha-3), 
#'   or the name of the state.
#'   For the complete list of entities and their search terms, 
#'   run the function without an argument (i.e. `code_states()`).
#'   Updates and suggestions welcome.
#' @param max_count Integer how many countries to search for in each element
#'   of the vector.
#'   Where more than one country is matched, the countries are returned as a set,
#'   i.e. in the format "\{AUS,NZL\}".
#'   By default `max_count = 1`, which will just return the first match.
#' @importFrom stringi stri_trans_general stri_detect_regex
#' @importFrom knitr kable
#' @examples
#' code_states(c("I went to England",
#'   "I come from Venezuela",
#'   "Did you know there was a Lunda Empire?",
#'   "I like both Australia and New Zealand"))
#' code_states(c("I went to England",
#'   "I come from Venezuela",
#'   "Did you know there was a Lunda Empire?",
#'   "I like both Australia and New Zealand"), max_count = 2)
#' @importFrom purrr map_chr
#' @export
code_states <- function(text, code = TRUE, max_count = 1){
  
  if(missing(text)) return(countryRegex)
  
  text <- stringi::stri_trans_general(text, "latin-ascii")
  
  purrr::map_chr(text, function(x) {
    out <- as.data.frame(countryRegex)[
                      which(stringi::stri_detect_regex(x, 
                                                       unlist(countryRegex[, 3]),
                                                 max_count = max_count,
                                                 opts_regex = list(case_insensitive = TRUE))),
                      ifelse(code, 1, 2)]
    if(length(out)==0) NA_character_ else 
      if(max_count > 1 && length(out)>1) 
        paste0("{",paste(out, collapse = ","),"}") else out
  })
}

# Regex ####
countryRegex <- dplyr::tribble(
  ~stateID, ~Label, ~Regex,
  ## A ####
  "ABK","Abkhazia","abkhaz",
  "ACH","Aceh","aceh",
  "AFG","Afghanistan","afghan|afghanistan",
  "AGO","Angola","angola",
  "ALB","Albania","albania|albanie",
  "ALT","Los Altos","los altos",
  "AND","Andorra","andorra|andorre",
  "ARE","United Arab Emirates","emirates|u[[:punct:]]a[[:punct:]]e[[:punct:]]|uae|united.?arab.?em|emirats arabes unis",
  "ARG","Argentina","argentin|argentine",
  "ARM","Armenia","armenia|armenie",
  "ASA","Assam","assam",
  "ASI","Asir","asir",
  "AST","Ashanti","ashanti",
  "ATG","Antigua and Barbuda","antigua|barbuda|antigua-et-barbuda",
  "AUH","Austria-Hungary","austria-hungary|austro-hungaria|aust-hung|aust empire|autria empire|austrian empire",
  "AUS","Australia","australia|australie|christmas is|cocos.*is|heard.is|mcdonald.is",
  "AUT","Austria","austria(?!-hungary| hungary)|austri.*emp|austrian|autriche",
  "AZA","Azande","azande",
  "AZE","Azerbaijan","azerbaijan|azerbaidjan|azerbeijan",
  ## B ####
  "BAD","Baden","baden",
  "BAV","Bavaria","bavaria",
  "BDI","Burundi","burundi",
  "BEL","Belgium","(?!.*luxem).*belgium|belgian|flemish|belgique|walloon|brussels|bruxelles",
  "BEN","Benin","benin|dahome|dahomey|benin",
  "BFA","Burkina Faso","burkina|faso|upper.?volta|burkina ?faso|burkna faso",
  "BGD","Bangladesh","bangladesh|(?=.*east).*paki?stan|bangladesh",
  "BGR","Bulgaria","bulgaria|bulgarie",
  "BHP","Bhopal","bhopal",
  "BHR","Bahrain","bahr.?in|bahre.?n|bahrein",
  "BHS","Bahamas","bahamas",
  "BHT","Bharatpur","bharatpur",
  "BIH","Bosnia and Herzegovina","herzegovina|bosnia|bosnie-herzegovine|herzego|bosnie",
  "BIK","Bikaner","bikaner",
  "BLR","Belarus","belarus|byelo|bielorussie|belarus",
  "BLZ","Belize","belize|(?=.*british).*honduras|belize",
  "BNJ","Benjermassin","benjermassin",
  "BOL","Plurinational State of Bolivia","(?!-).bolivia|bolivie|^bolivia$|bolivia..pluri",
  "BOU","Burgundy","burgundy|bourgogne|burgandy",
  "BPR","Bahawalpur","bahawalpur",
  "BRA","Brazil","brazil|brasil|bresil|bresil",
  "BRB","Barbados","barbados|barbade",
  "BRE","Bremen","bremen",
  "BRN","Brunei Darussalam","brun.?i|brunei darussalam",
  "BTN","Bhutan","bhutan|bhoutan",
  "BUK","Bukhara","bukhara",
  "BUR","Urundi","\\burundi",
  "BWA","Botswana","botswana|bechuana|botswana",
  ## C ####
  "CAF","Central African Republic","central.african.republic|cen.* afr.* re.*|republique centrafricaine|centrafrique|centrafricaine|cen afr emp",
  "CAN","Canada","canada|canadian|canada|newfoundland",
  "CAY","Cayor","cayor|Kajoor",
  "CHE","Switzerland","switz|swiss|suisse",
  "CHL","Chile","chile|chili",
  "CHM","Chamba","chamba",
  "CHN","China","(?!.*\\bmac)(?!.*\\bhong)(?!.*\\btai)(?!.*\\brep).*china|(?=.*peo)(?=.*rep).*china|chine|macao|china",
  "CIV","Cote d'Ivoire","ivoire|ivory|cote d'ivo.+",
  "CMR","Cameroon","cameroon|cameroun|cameroun",
  "COD","Democratic Republic of the Congo","dem.*congo|congo(.+)?dem|d[[:punct:]]r[[:punct:]]c[[:punct:]]|belgian.?congo|congo.?free.?state|kinshasa|zaire|l.opoldville|drc| droc |rdc|droc|congo-kinshasa|congo dr|d.r. of the congo|congo.+kin|dr.congo",
  "COG","Congo","(?<!democratic )rep.*congo|brazz|congo.rep|congo..rep|congo..bra|^congo$",
  "COK","Cook Islands","cook.is|iles.cook",
  "COL","Colombia","(?<!great |gran )colombia|colombie",
  "COM","Comoros","comoro|comores",
  "CPV","Cape Verde","verde|cap-vert|cabo verde|cap vert",
  "CRI","Costa Rica","costa.?rica|costa rica",
  "CUB","Cuba","\\bcuba|cuba",
  "CUT","Cutch","cutch|Kutch|Kachchh",
  "CYP","Cyprus","cyprus|chypre",
  "CZE","Czech Republic","(?=.*rep).*czech|czechia|bohemia|czechoslovakia|tchequie|czech|tchequ.+",
  ## D ####
  "DDR","German Democratic Republic","german.dem.*rep|democratic.?rep.*germany|east.germany|ddr|german.dr",
  "DEU","Germany","(?<!east )germany|german(?!.*democratic) republic|prussia|allemagne|german.fr|german.fed|alsace-lorraine|brunswick|berlin",
  "DFR","Darfur","darfur",
  "DIR","Dir","\\bdir\\b",
  "DJA","Fouta Djallon","fouta djallon",
  "DJI","Djibouti","djibouti",
  "DMA","Dominica","dominica\\b|dominique",
  "DNK","Denmark","denmar|danish(?!.*waters)|danemark|greenland",
  "DOM","Dominican Republic","domin.*rep|republique dominicaine|santo domin",
  "DRV","Annam","annam",
  "DZA","Algeria","ottoman.?algeria|algerie|(?<!ottoman )algeria",
  "DZG","Free City of Danzig","danzig",
  ## E ####
  "EAZ","Zanzibar","zanzibar",
  "ECU","Ecuador","ecuador|equateur",
  "EGY","Egypt","egypt|egypte|united arab republic|(?<![:alpha:])uar(?![:alpha:])",
  "EHT","State of Haiti","state of haiti",
  "ERI","Eritrea","eritrea|erythr[ee]e",
  "ESH","Western Sahara","western.sahara|sahrawi|sahara occidental",
  "ESP","Spain","spain|castile|spanish(?! guinea)|espagne|canary|granada",
  "EST","Estonia","estonia|estonie",
  "ETH","Ethiopia","ethiopia|abyssinia|ethiopie|eth.pia",
  "ETS","Eastern Turkistan","eastern turkistan",
  "EUE","European Union","european union|\\beu\\b|\\be[[:punct:]]u[[:punct:]]\\b|european.union|union.euro|european.comm|european.economic.comm",
  ## F ####
  "FIN","Finland","finland|finlande|\\baland\\b",
  "FJI","Fiji","fiji|fidji",
  "FNJ","Funj","funj",
  "FRA","France","(?!.*\\bdep)(?!.*martinique).*france|french.?republic|gaul|france|french|guadeloupe|burgundy|mayotte|new.caledonia|martinique|r[ee]union|barthelemy|t.martin|st\\..martin|miquelon|futuna",
  "FRO","Faroe Islands","faroe|faeroe|iles feroe",
  "FSM","Federated States of Micronesia","micronesia|micron[ee]sie",
  "FTO","Fouta Toro","fouta toro|futa",
  ## G ####
  "GAB","Gabon","gabon",
  "GBR","United Kingdom","england|united.?kingdom|britain|british(?!.*hondur| east africa)|\\buk\\b|\\bu[[:punct:]]k[[:punct:]]\\b|royaume-uni|bermuda|anguilla|cayman|channel.is|akrotiri|dhekelia|falkland.is|virgin.is|gibraltar|guernsey|guernesey|jersey|isle of man|northern.ireland|pitcairn|helena|norfolk|montserrat|south.sandwich.is|caicos|grande.bretagne|the uk",
  "GCL","Gran Colombia","gran colombia|great colombia",
  "GEO","Georgia","(?<!south )georgia|georgie|georgie",
  "GHA","Ghana","ghana|gold.?coast|ghana",
  "GIN","Guinea","(?<!new |spanish |portuguese |equatorial |papua new )guinea(?!.*equ|-bissau| bissau)|(?<!nouvelle.)guinee(?!-bissa| equatoriale)",
  "GMB","Gambia","gambia|gambie",
  "GNB","Guinea-Bissau","bissau|(?=.*portu).*guinea|guin[ee]e.bissa[uo]",
  "GNQ","Equatorial Guinea","guine.*eq|eq.*guine|(?=.*span).*guinea|guin[ee]e [ee]quatoriale",
  "GRC","Greece","greece|hellenic|hellas|greek|gr[e]ce",
  "GRD","Grenada","grenada|grenade",
  "GTM","Guatemala","guatemala",
  "GUY","Guyana","guyana|british.?guiana|guyana",
  "GWA","Gwalior","gwalior",
  ## H ####
  "HAN","Hanover","hanover",
  "HAW","Hawaii","hawaii",
  "HBG","Hamburg","hamburg",
  "HEJ","Hejaz","hejaz",
  "HKG","Hong Kong","hong.kong|r.a.s. chinoise de hong kong",
  "HND","Honduras","(?<!british )honduras|honduras",
  "HRV","Croatia","croatia|croatie",
  "HSE","Hesse Electoral","hesse.*lectoral|hesse.kassel|hesseelect",
  "HSG","Hesse Grand Ducal","hess.*gran.*ducal|hesse.darmstadt|hessegrand",
  "HTI","Haiti","(?<!state of )haiti|hayti",
  "HUN","Hungary","(?<!austria-|austria )hungary|hungarian|hongrie",
  ## I ####
  "IDN","Indonesia","indonesia|indonesie",
  "IND","India","india(?!.*ocea)|inde",
  "INO","Indore","indore",
  "IPH","Perak","perak",
  "IRL","Ireland","(?=.*(?<!northern )ireland)(?=.*(?<!britain and )ireland)|irish|irlande",
  "IRN","Islamic Republic of Iran","\\biran|persia|iran",
  "IRQ","Iraq","iraq|mesopotamia|irak",
  "ISL","Iceland","iceland|islande",
  "ISR","Israel","israel",
  "ITA","Italy","italy|italian|italo|italie",
  ## J ####
  "JAM","Jamaica","jama.?ca|jama[i]que",
  "JMK","Jimma-Kakka","jimma-kakka",
  "JOD","Jodhpur","jodhpur",
  "JOH","Johore","johor",
  "JOR","Jordan","jordan|jordanie",
  "JPN","Japan","japan|nippon|japon",
  "JPR","Jaipur","jaipur",
  ## K ####
  "KAF","Kaffa","kaffa",
  "KAS","Kasanje","kasanje",
  "KAT","Kathiri Sultanate","kathiri sultanate",
  "KAZ","Kazakhstan","kazak|kazakhstan",
  "KED","Kedah","kedah",
  "KEL","Kelantan","kelantan",
  "KEN","Kenya","kenya|british.?east.?africa|east.?africa.?prot|kenya",
  "KGZ","Kyrgyzstan","kyrgyz|kirghiz|kirghizistan",
  "KHI","Khairpur","khairpur|khayrpur",
  "KHM","Cambodia","cambodia|kampuchea|khmer|cambodge",
  "KHV","Khiva","khiva",
  "KIR","Kiribati","kiribati",
  "KLT","Kalat","kalat",
  "KNA","St. Kitts and Nevis","kitts|nevis|saint-christophe.et.nieves|st.kitt",
  "KNB","Kanem-Bornu","kanem-bornu",
  "KOK","Kokand","kokand",
  "KON","Kongo Kingdom","kongo kingdom",
  "KOR","Republic of Korea","^korea$|(?<!peoples )republic.of.korea|coree.*sud|republique.de.coree|south.korea|korea.{1,2}rep|korea.{1,2}rok|korea.{1,2}south",
  "KOS","Kosovo","kosovo",
  "KOT","Kotah","kotah",
  "KPT","Kapurthala","kapurthala",
  "KRG","Karangasem (Bali and Lombok)","karangasem (bali and lombok)",
  "KTA","Kaarta","kaarta",
  "KUB","Kuba","kuba",
  "KWT","Kuwait","kuwait|koweit",
  "KZB","Kazembe","kazembe",
  ## L ####
  "LAO","Lao People's Democratic Republic","laos|lao.pdr|lao.people|lao, p.*d.*r|lao.*p\\.d\\.r",
  "LBN","Lebanon","lebanon|liban",
  "LBR","Liberia","liberia|liberia",
  "LBY","Libya","libya|tripolitania|libye",
  "LCA","St. Lucia","lucia|sainte-lucie",
  "LIE","Liechtenstein","liechtenstein|liechtstein",
  "LIM","Enarya (Limmu)","enarya (limmu)",
  "LIP","Lippe","lippe",
  "LKA","Sri Lanka","sri.?lanka|ceylon|sri lanka",
  "LSO","Lesotho","lesotho|basuto.*",
  "LTU","Lithuania","lithuania|lituanie|lithuanie",
  "LUB","Luba","luba",
  "LUN","Lunda Empire","lunda empire|kingdom of lunda",
  "LUX","Luxembourg","(?<!belgian )luxem|luxembourg",
  "LVA","Latvia","latvia|lettonie",
  ## M ####
  "MAR","Morocco","morocco|\\bmaroc|maroc",
  "MAS","Massina","massina|maasina|macina",
  "MCO","Monaco","monaco",
  "MDA","Republic of Moldova","moldov|moldavia|b(a|e)ssarabia|moldavie",
  "MDG","Madagascar","madagascar|malagasy|madagasacar",
  "MDK","Mandinka Empire (Wassulu)","mandinka empire (wassulu)",
  "MDV","Maldives","maldive|maldives",
  "MEC","Mecklenburg Schwerin","mecklenbur.*schwerin|mecklenbur",
  "MEX","Mexico","mexic|mexique",
  "MHL","Marshall Islands","marshall|iles marshall",
  "MIN","Minangkabau","minangkabau",
  "MKD","North Macedonia","macedonia|fyrom|former yugoslav republic of mac.*|mac[ee]doine",
  "MLI","Mali","\\bmali",
  "MLT","Malta","malta|malte",
  "MMR","Myanmar","myanmar|burma|myanmar (birmanie)",
  "MNE","Montenegro","(?!.*serbia).*montenegro|mont[ee]n[ee]gro",
  "MNG","Mongolia","mongol|mongolie",
  "MOD","Modena","modena",
  "MOS","Yatenga (Mossi)","yatenga|mossi",
  "MOZ","Mozambique","mozambique",
  "MPR","Manipur","manipur",
  "MRT","Mauritania","mauritania|mauritanie",
  "MUS","Mauritius","mauritius|maurice",
  "MWI","Malawi","malawi|nyasa|malawi",
  "MYS","Malaysia","malaysia|malaisie|malay",
  ## N ####
  "NAG","Nagpur","nagpur",
  "NAM","Namibia","namibia|namibie",
  "NAS","Nassau","nassau",
  "NER","Niger","niger(?!ia)",
  "NGA","Nigeria","nig[ee]ria",
  "NIC","Nicaragua","nicaragua",
  "NIU","Niue","niue|niou[ee]",
  "NLD","Netherlands","(?!.*ant)(?!.*carib).*netherlands|netherlands.antil|dutch.antil|aruba|curacao|pays-bas|bonaire|holland|(?!.*martin)(?!.*saba).*maarten|saint-martin (partie neerlandaise)",
  "NOR","Norway","norway|norweg|norv[e]ge|bouvet|svalbard",
  "NPL","Nepal","n[ee]pal",
  "NRU","Nauru","nauru",
  "NZL","New Zealand","new.?zealand|nouvelle.z[ee]lande",
  ## O ####
  "OFS","Orange Free State","orange free state|ovs",
  "OLD","Oldenburg","oldenburg",
  "OMN","Oman","\\boman|trucial|omaan",
  "OVB","Ovimbundu","ovimbundu",
  "OYO","Oyo","oyo",
  ## P ####
  "PAH","Pahang","pahang",
  "PAK","Pakistan","(?<!east |eastern )paki?stan|pakistan",
  "PAL","Palembang","palembang",
  "PAN","Panama","panama",
  "PER","Peru","peru|p[ee]rou",
  "PES","Peshwa","peshwa",
  "PHL","Philippines","philippines",
  "PLW","Palau","palau|palaos",
  "PMA","Parma","parma",
  "PNG","Papua New Guinea","papua|new.?guinea|papouasie",
  "POL","Poland","poland|polish|pologne",
  "PPR","Polish Peoples Republic","polish peoples republic",
  "PRK","Democratic People's Republic of Korea","dprk|d.p.r.k|korea.+(d.p.r|dpr|north|dem.*peo.*rep)|(d.p.r|dpr|dem.*peo.*rep.*).+korea|north korea|cor[e]e.*nord|korea.dem|korea..dem|korea..peo|korea.pr|korea..pre-1950",
  "PRT","Portugal","portugal|portuguese|portugal|azores|acores",
  "PRY","Paraguay","paraguay(?! river)|paraguay",
  "PSE","Gaza Empire","palestin|\\bgaza|west.?bank|territoires palestiniens",
  "PUN","Punjab","punjab|panj.?b|panj-.?b",
  ## Q ####
  "QAT","Qatar","qatar",
  "QUA","Qu'aiti Sultanate","qu'aiti|quaiti",
  ## R ####
  "ROU","Romania","r(o|u|ou)mania|roumanie",
  "RUS","Russian Federation","russia|russian fed.*|soviet.?union|union of soviet|u[[:punct:]]s[[:punct:]]s[[:punct:]]r[[:punct:]]|socialist.?republics|USSR|RSFSR|russie|un.*sov.*soc.*rep",
  "RVN","Republic of Vietnam","(?<!socialist|democratic) republic.of.viet.?nam|republic.of.viet.?nam|viet.?nam rep|south.viet.?nam|viet.?nam.south|svietnam|vietnam, s|vietnam, r",
  "RWA","Rwanda","rwanda|rwandese|ruanda",
  ## S ####
  "SAL","Saloum","saloum",
  "SAR","Sardinia","sardinia|Sardinia",
  "SAU","Emirate of Diriyah","sa.*arabia|first saudi state|emirate of dir.?iyah|arabie saoudite",
  "SAW","Sawantvadi","sawantvadi|sawantwadi",
  "SAX","Saxony","saxony",
  "SDN","Sudan","(?<!south )sudan|soudan|funj sultanate of sennar",
  "SEG","Segou","segou|s.?gou",
  "SEL","Selangor","selangor",
  "SEN","Senegal","s[ee]n[ee]gal",
  "SGP","Singapore","singapore|singapour",
  "SHO","Shoa","shoa|shewa|shua|showa|shuwa",
  "SIA","Siak","siak|siunia|syunik",
  "SIC","Two Sicilies","two.?sicilies|2.?sicilies",
  "SID","Sind","sind|sindh",
  "SIK","Sikkim","sikkim",
  "SIR","Sirohi","sirohi",
  "SLB","Solomon Islands","solomon|salomon",
  "SLE","Sierra Leone","sierra.leo",
  "SLV","El Salvador","el.?salvador|salvador",
  "SMR","San Marino","san.?marino|saint-marin",
  "SOK","Sokoto","sokoto",
  "SOM","Somalia","somali|somalie",
  "SOT","South Ossetia","south ossetia",
  "SRB","Serbia","(?!.*monte).*serbia|serbie|yugoslav",
  "SSD","South Sudan","south.sudan|soudan du sud",
  "STP","Sao Tome and Principe","s[a]o.tom[ee]|sao tome-et-principe|saotome",
  "SUL","Sulu","sulu",
  "SUR","Suriname","surinam|dutch.?guiana|suriname",
  "SVK","Slovakia","(?<!czecho)slovak|slovaquie|slovaque",
  "SVN","Slovenia","sloven|slov[ee]nie",
  "SWA","Swat","^swat$|dera yusufzai",
  "SWE","Sweden","swed|su[e]de",
  "SWZ","Eswatini","swaziland|eswatini",
  "SXA","Saxe-Altenburg","saxe-atenburg|saxe-altenburg",
  "SXG","Saxe-Coburg-Gotha","saxe-coburg-gotha",
  "SXM","Saxe-Meiningen-Hidburghausen","saxe.meiningen.hidburghausen",
  "SXW","Saxe-Weimar-Eisenach","saxe.wiemar.eisenach|saxe-weimar-eisenach",
  "SYC","Seychelles","seychell|seychelles",
  "SYR","Syrian Arab Republic","syria|syrie",
  ## T ####
  "TBT","Tibet","tibet",
  "TCD","Chad","chad|tchad",
  "TER","Terengganu","terengganu|trengganu|tringganu",
  "TEX","Texas","texas",
  "TGO","Togo","togo",
  "THA","Thailand","thailand|siam|tha[i]lande",
  "TJK","Tajikistan","tajik|tadjikistan",
  "TKL","Tokelau","tokelau",
  "TKM","Turkmenistan","turkmen|turkmenistan|turkmenistan",
  "TLS","Timor-Leste","(?=.*leste).*timor|(?=.*east).*timor|timor oriental|timor.?leste",
  "TOK","Tokolor","tokolor",
  "TON","Tonga","tonga",
  "TRA","Transvaal","transvaal",
  "TTO","Trinidad and Tobago","trinidad|tobag|trinite",
  "TUN","Tunisia","tunisia|tunisie",
  "TUR","Turkiye","turkey|t[u]rkiye|turquie|ottoman emp",
  "TUS","Tuscany","tuscany",
  "TUV","Tuvalu","tu[vl]a[lv]u",
  "TWN","Chinese Taipei","ta[i]wan|taipei|formosa",
  "TZA","United Republic of Tanzania","tanzania|tanzanie|tanganyika",
  ## U ####
  "UGA","Uganda","uganda|buganda|ouganda",
  "UKR","Ukraine","ukrain|ukraine|ukrainian ssr|ukrainian soviet",
  "UPC","United Provinces of Central America","united provinces of central america|United Provinces of CA|United Province of CA|United Province CA",
  "UPR","Udaipur","udaipur",
  "URY","Uruguay","uruguay",
  "USA","United States of America","united states of america|united.states(?!.*of brazil)|u[[:punct:]]s[[:punct:]]a[[:punct:]]|u[[:punct:]]s[[:punct:]](?!.*s[[:punct:]]r[[:punct:]])|\\busa\\b|\\bus\\b|etats-unis|northern.mariana|puerto.rico|guam|(?<![:alpha:])usa(?![:alpha:])",
  "UZB","Uzbekistan","uzbek|ouzb[ee]kistan",
  ## V ####
  "VAT","Holy See","holy.?see|vatican|papal.?st|etat de la cite du vatican|saint.siege",
  "VCT","St. Vincent and the Grenadines","vincent|saint-vincent-et-les-grenadines|st.vin",
  "VEN","Bolivarian Republic of Venezuela","v[ee]n[ee]zu[ee]la",
  "VNM","Viet Nam","(?<=socialist|democratic|north).*viet.?nam|viet.?nam socialist|viet.?nam democratic|\\bviet.?nam$|viet.?nam.?dem|dem.?rep.?viet.?nam|viet.?nam n|viet.?nam, n|viet.?nam, d|viet.?nam d|viet.?nam",
  "VUT","Vanuatu","vanuatu|new.?hebrides|vanuatu",
  ## W ####
  "WAD","Wadai","wadai",
  "WRT","Wuerttemburg","w(ue)rttemburg|w.rtemberg",
  "WSM","Samoa","(?!.*amer).*samoa|samoa",
  ## Y ####
  "YEK","Yeke Kingdom","yeke kingdom",
  "YEM","Yemen","(?<= arab|north|sana).*yemen|yemen(?= arab)|yemen(?!.peo)",
  "YPR","Yemen Peoples Republic","(?=.*peo).*yemen|(?!.*rep)(?=.*dem).*yemen|(?=.*south).*yemen|(?=.*\\bp\\.?d\\.?r).*yemen|\\baden",
  ## Z ####
  "ZAF","South Africa","south.africa|s\\. africa|afrique du sud|so.africa|venda|bophutatswana|transkei|ciskei",
  "ZIN","Zinder (Damagaram)","zinder (damagaram)",
  "ZMB","Zambia","zambia|northern.?rhodesia|zambie",
  "ZUL","Zululand","zululand",
  "ZWE","Zimbabwe","zimbabwe|(?<!northern )rhodesia|zimbabwe"#,
  ## Other ####
  # "EC","European Community","european economic community|european community|e[[:punct:]]c[[:punct:]]|(?<![:alpha:])eec(?![:alpha:])|european.comm|euratom|union.euro|eu-15",
  # "AU","African Union","african.union",
  # "EFTA","European Free Trade Association","(?<![:alpha:])efta(?![:alpha:])|european free trade association"
)

# Useful resource:
# https://stringi.gagolewski.com/weave/regular_expressions.html#
